### ISSUE TITLE
Quest 9176 - unable to finish

### ISSUE THREAD

**Issue by wormogo** [wormogo/Fixes_for_SPP_Project#3]
Unable to finish Quest 9176

**Comment by wormogo** [comment]
https://cdn.discordapp.com/attachments/397484550839861251/475986695393771552/WoWScrnShot_080618_141944.jpg

**Comment by Fatliner** [comment]
I tried it with warlock and havent problem.
![wowscrnshot_092318_192353](https://user-images.githubusercontent.com/42327837/45930958-d7a0a900-bf66-11e8-8b3b-d0dc2e2dd5ae.jpg) 
![wowscrnshot_092318_192404](https://user-images.githubusercontent.com/42327837/45930964-e25b3e00-bf66-11e8-9dd9-54cf9b5c1067.jpg)

**Comment by wormogo** [comment]
Quest has been tested and works fine. Thank you Fatliner! Closing ticket.
