### ISSUE TITLE
(Spell) Unholy DK urgent problem

### ISSUE THREAD

**Issue by ivan2view** [wormogo/Fixes_for_SPP_Project#36]
Unholy DK doesn't work.
1)Using Outbreak (spell=77575) the target gets Blood Plague from Blood DK (spell=55078)  and  Frost Fever from Frost DK (spell=55095), instead of Virulent Plague (spell=191587) [https://www.wowhead.com/spell=191587/virulent-plague]  
1.1 The Outbrake Deals (38% of Attack power) Shadow damage and surrounds the target in a miasma lasting for 6 sec that causes the target, only target (**but must all nearby enemies**), to be infected with Blood Plague and  Frost Fever ( **but should with Virulent Plague**)
2)There is no Festering Wound (spell=194310) at all
2.1)  Festering Strike (spell=85948) doesn't   infect the target with 2 to 4 Festering Wounds, because of its missing.
2.2) Scourge Strike does't  cause 1 Festering Wound to burst because  of its missing

**Comment by bySenom** [comment]
some spells was fixed by Ashamane

**Comment by wormogo** [comment]
Thanks BySenom!

From Ashamane:

"Spells/DK Fix lot of unholy spells & talents

Including :

- Festering Wound
- Epidemic
- Virulent Plague
- Virulent Eruption
- Outbreak
- Defile damages
- Defile mastery
- Unholy Frenzy
- Pestilent Pustules
- Castigator
- Unholy Vigor
- Blighted Rune Weapon"

Please check if its working or not.

**Comment by wormogo** [comment]
It has been fixed today on Ashamane and applied to SPP repack. Issue has been resolved. Closing
