### ISSUE TITLE
Stormwind Royal Guard needs update. [Elwynn Forest]

### ISSUE THREAD

**Issue by Danuliz** [wormogo/Fixes_for_SPP_Project#37]
So can someone update SRG at some point? They seem to have wrong aura about carrier flag. With 
 that they are added random locations + missing spots. They also  seem to not have they waypoints either. They are in group as 9 members and they spawn at stormwind very gate and travel into bridge by Eastvale Logging Camp (place where lvl 9 continues they quests) and when they arrives they destination (wp) they will disappear > respawns in sw gate and so on. They seem to had wrong aura spell id and this is the one what they needs to: [https://www.wowhead.com/spell=78855/stormwind-flag-carrier](https://www.wowhead.com/spell=78855/stormwind-flag-carrier) I saw in database too that they are missing they horses when you spawn them and they horse or aka mount id is: 29284

So they need they formation, waypoints, mount id, right spawn point at gate and they disappear when they arrive near the bridge of Eastvale Logging Camp and they aura what is that Sw flag carrier. if you guys need to know how they need to formation here is the picture how it is done. [https://wow.zamimg.com/uploads/screenshots/normal/194457-stormwind-royal-guard-royal-guard-on-their-way-to-goldshire.jpg](https://wow.zamimg.com/uploads/screenshots/normal/194457-stormwind-royal-guard-royal-guard-on-their-way-to-goldshire.jpg)
That's all cheers. :)
- [ ] Check creature addon, creature group and fix
- [ ] Check waypoint on offi and make sniff data
- [ ] Check the aura if those have one and correct if needed
- [ ] Make c++ if not available or SAI for guards

**Comment by takasi689** [comment]
I'll try to sniff _waypoints_ from blizzard.

**Comment by Danuliz** [comment]
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (42218, 0, 29284, 0, 1, 0, 0, 0, 0, '78855');

**Comment by wormogo** [comment]
Issue has been resolved as Ashamane updates show today.

AshamaneCore:
- Some path for Stormwind npcs
- Path for Stormwind patrol

Closing the ticket, let me know if something is missing or wrong in a separate ticket.

Thank you!
