### ISSUE TITLE
Quest 29790 Passing Wisdom

### ISSUE THREAD

**Issue by chaosskynet** [wormogo/Fixes_for_SPP_Project#44]
after you start the quest the master disapear and talk you nothing.
with .completequest [Passing Wisdom] the ? marker will shown on minimap but there is no npc and other objects

**Comment by wormogo** [comment]
@Monady : can you please take look into this as I tried to find the correct phase spell without success. Last ugly fix is mine which seems does not work on SPP.

**Comment by wormogo** [comment]
Issue has been resolved, now the quest is fixed.
