### ISSUE TITLE
resurrection angel Bug

### ISSUE THREAD

**Issue by kaelhorda** [wormogo/Fixes_for_SPP_Project#48]
el npc 6491 .........https://es.wowhead.com/npc=6491/%C3%A1ngel-de-la-resurrecci%C3%B3n 
cuando los jugadores mueren y quieren revivir, el ángel no permite hacerlo.
![203dcb0d-e978-4131-9e16-e05ce4063842](https://user-images.githubusercontent.com/30556467/45244512-bf216500-b2bd-11e8-8408-48f32b535b6c.jpg)
![db5a65be-6e43-424f-a6e7-10df5906e676](https://user-images.githubusercontent.com/30556467/45244513-bf216500-b2bd-11e8-92d0-c4ec8679def2.jpg)

**Comment by Fatliner** [comment]
`UPDATE `creature_template` SET `npcflag`=16384 WHERE `entry`=6491;`

**Comment by wormogo** [comment]
@Fatliner : is it resolved? I am sorry have not checked until now. Let me know if resolved and I will close thise ticket. Thx!

**Comment by Fatliner** [comment]
It is resolved.

**Comment by wormogo** [comment]
Thank you @Fatliner ! Closing ticket based upon issue is resolved.
