### ISSUE TITLE
Worldserver Crash - Update from 09/04/18

### ISSUE THREAD

**Issue by dremack13** [wormogo/Fixes_for_SPP_Project#49]
**Describe the bug**
After retrieving an update last night, when starting the worldserver (Win64), am receiving the following error before auto-close: 

ERROR 1062 (23000) at line 23: Duplicate entry '280000009' for key 'PRIMARY'
Applying of file '../../sql/ashmane/world/2018_09_04_01_world_quest.sql' to database 'world' failed!

**To Reproduce**
1. Run SingleCore server launcher
2. Select "2 - Start servers (Win64)"

**Expected behavior**
Worldserver will load.

**Screenshots**
![image](https://user-images.githubusercontent.com/43097421/45257416-dfebc800-b35a-11e8-98d7-457ff63b74e1.png)

**Comment by wormogo** [comment]
Issue comes from a duplicate entry in your db so you need to delete from your manually or do a world reset from service menu in launcher.
