### ISSUE TITLE
Adamantite Ore Prospecting - Wrong loot table

### ISSUE THREAD

**Issue by Obivion** [wormogo/Fixes_for_SPP_Project#52]
Prospecting of Adamantite Ore is giving the wrong loot table and is handing out blue items and not the green gems.

Attached is a SQL that corrects the loot tables by using Fel Iron Ore as the base, as they have the same prospecting gem output, just with different % chance. Data is based from wowhead.

[prospecting adamantite ore fix.sql.txt](https://github.com/wormogo/Fixes_for_SPP_Project/files/2369275/prospecting.adamantite.ore.fix.sql.txt)

**Comment by wormogo** [comment]
Proposed fix has been applied to SPP repository.

Thank you for the fix!
