### ISSUE TITLE
Northrend Ore Prospecting - Wrong loot table

### ISSUE THREAD

**Issue by Obivion** [wormogo/Fixes_for_SPP_Project#64]
Prospecting of Northrend Ore is giving the wrong loot table and is handing out blue items, these reference 3 loot pools with blue items in.

Attached is a SQL that corrects the loot tables by reassigning what appears to be the correct reference_loot entries. % chance on gems appears roughly right based on the Wowhead %

[prospecting northrend ore fix.sql.txt](https://github.com/wormogo/Fixes_for_SPP_Project/files/2380009/prospecting.northrend.ore.fix.sql.txt)

(I think I will go check cata ores later since we are going there in a few days...)

**Comment by wormogo** [comment]
Proposed fix is added to repository. Thank you @Obivion !

Also it is released to SPP server too.
