### ISSUE TITLE
Timeless_chect_fix from Wormogo don't work

### ISSUE THREAD

**Issue by bySenom** [wormogo/Fixes_for_SPP_Project#65]
**Describe the bug**
The containers fix from Wormogo don't work

**To Reproduce**
1. use [.ad 102291]
2. Click on the item
3. look in your inventory
4. item are not exist

**Expected behavior**
When you add the container and click on it you dont get a specific item

https://github.com/wormogo/Fixes_for_SPP_Project/commit/19f4ffd5b31a061a5788b98bfe431ad9ff6e8e62

**Comment by wormogo** [comment]
Need to rework the fix. Test has been accepted from community and need to validated on test server

**Comment by takasi689** [comment]
Can someone try this if it works 😊

-- fix Timeless Chest 220994 missing loot template

DELETE FROM `gameobject_loot_template` WHERE entry = 220994

INSERT INTO `gameobject_loot_template` (Entry, Item, Chance, MinCount, MaxCount) VALUES (220994, 104202, 15, 1, 1);
INSERT INTO `gameobject_loot_template` (Entry, Item, Chance, MinCount, MaxCount) VALUES (220994, 103982, 0.70, 1, 1);
INSERT INTO `gameobject_loot_template` (Entry, Item, Chance, MinCount, MaxCount) VALUES (220994, 102318, 10, 1, 1);

UPDATE `gameobject_template` SET Data1 = 220994 WHERE entry = 220944;

**Comment by takasi689** [comment]
Timeless chest have loot in DB,therefore im closing this.
