### ISSUE TITLE
NPC Issue in Undead starting area

### ISSUE THREAD

**Issue by beholder242** [wormogo/Fixes_for_SPP_Project#77]
NPC ID's 1504 and 1505 (Spiders in the Deathknell area) currently marked as hostile, but do not appear to have an aggressive AI.  Should be remarked as neutral, as in retail.
![retail - deathknell spiders - 2](https://user-images.githubusercontent.com/42948155/46575441-b5e9ed80-c97a-11e8-8b97-e7126c12b013.png)
![private - deathknell spiders](https://user-images.githubusercontent.com/42948155/46575442-b5e9ed80-c97a-11e8-9563-d657ef99f9c2.png)
![retail - deathknell spiders - 1](https://user-images.githubusercontent.com/42948155/46575443-b5e9ed80-c97a-11e8-9633-b20365e6801a.png)

**Comment by Thordekk** [comment]
Fixed, the creatures was with incorrect flag
