### ISSUE TITLE
green world map

### ISSUE THREAD

**Issue by bcody8780** [wormogo/Fixes_for_SPP_Project#78]
**Describe the bug**
my world map is flat green anywhere i discover
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Thordekk** [comment]
Can you explain the problem or share a screenshoot?

**Comment by bcody8780** [comment]
![wowscrnshot_101618_181526](https://user-images.githubusercontent.com/44003382/47186910-f89ab680-d2e6-11e8-9edb-5b7c208b29a7.jpg)

**Comment by wormogo** [comment]
As we have not received further information or comment, I am closing the ticket
