### ISSUE TITLE
worldserver.exe crash  by trying to load creature database after latest update

### ISSUE THREAD

**Issue by jukatax** [wormogo/Fixes_for_SPP_Project#87]
After today's update worldserver.exe crashes when trying to load creature database. I have used all items 1-4 from service menu to try and fix the issue but it still persist:
>> Loaded 460 creature base stats in 12 ms
Loading Creature Data...
Could not load VMAP name:Transport: Howling Fjord Sister Mercy (Quest), id:594, x:31, y:39 (vmap rep.: x:31, y:39)
Could not load VMAP name:Transport: Howling Fjord Sister Mercy (Quest), id:594, x:32, y:39 (vmap rep.: x:32, y:39)
Could not load VMAP name:Transport: Howling Fjord Sister Mercy (Quest), id:594, x:31, y:38 (vmap rep.: x:31, y:38)
Could not load VMAP name:Transport: Howling Fjord Sister Mercy (Quest), id:594, x:32, y:38 (vmap rep.: x:32, y:38)
Could not load VMAP name:Transport: Orgrimmar to Thunder Bluff, id:647, x:32, y:32 (vmap rep.: x:32, y:32)
Could not load VMAP name:Transport: Orgrimmar to Thunder Bluff, id:647, x:31, y:32 (vmap rep.: x:31, y:32)

d:\trinitybuilder\source\spp-ashamanecore\src\common\collision\management\mmapmanager.cpp:199 in MMAP::MMapManager::loadMapImpl ASSERTION FAILED:
  data
  
at this point worldserver.exe crashes.

Thanks

**Comment by romchikus82** [comment]
similar problem, join ...

![image](https://user-images.githubusercontent.com/44382914/47323751-c03c0500-d665-11e8-86c1-350aa5902342.png)

After a while, the server went up ...

**Comment by TheGiuxeppeh** [comment]
`

###############################################################################

  SSSSs   Ss                SSs            SSSSSs
 Ss   Ss                     Ss           Ss    Ss
Ss     S  Ss Ss           SS Ss  SSSSS   Ss         SSSSs   Ss SSs   SSSSSs
 Ss      SSs Sssss    SSSSSs Ss Ss    Ss Ss        Ss   Ss  SSSs Ss Ss    Ss
  SSSSs   Ss Ss  Ss  Ss   Ss Ss Ss    Ss Ss       Ss     Ss Ss      Ss    Ss
      Ss  Ss Ss   Ss Ss   Ss Ss SSSSSS   Ss       Ss     Ss Ss      SSSSSSs
 S     Ss Ss Ss   Ss Ss   Ss Ss Ss       Ss       Ss     Ss Ss      Ss
 Ss   Ss  Ss Ss   Ss  SSSSSs Ss Ss     s  Ss    S  Ss   Ss  Ss      Ss
  SSSSs   Ss Ss   Ss      Ss Ss  SSSSSs    SSSSS    SSSSs   Ss       SSSSSSs
                          Ss
                      SSSSs                    <<< Based on AshamaneCore >>>

 https://github.com/AshamaneProject/AshamaneCore
###############################################################################

Using configuration file D:/WOW LEGION GROUP/SingleCore_Legion_v3 MAIN/SingleCore_Legion/spp-legion/Realms/1/Settings/world.conf.
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.67.0
Updating Auth database...
>> Auth database is up-to-date! Containing 38 new and 0 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 23 new and 0 archived updates.
Updating World database...
>> World database is up-to-date! Containing 279 new and 931 archived updates.
Updating Hotfixes database...
>> Hotfixes database is up-to-date! Containing 17 new and 45 archived updates.
Realm running as realm ID 1
Using World DB: ADB 735.00
Using enUS DBC Locale
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Using DataDir ..\..\Server\Data/
WORLD: MMap data directory is: ..\..\Server\Data/mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: ..\..\Server\Data/vmaps
Initialize PlayerDump...
>> Initialized 384 PlayerDump ColumnDefinitions in 429 ms.
Loading Trinity strings...
>> Loaded 1086 trinity strings in 70 ms
Initialize data stores...
>> Initialized 253 DB2 data stores in 87759 ms
>> Loaded 190 hotfix records in 45 ms
>> Loading Cinematic Camera files
>> Loaded 34 cinematic waypoint sets in 299 ms
>> Initialized 29 GameTables in 265 ms
Loading SpellInfo store...
>> Loaded SpellInfo store in 1250 ms
Loading SpellInfo corrections...
>> Loaded SpellInfo corrections in 146 ms
Loading SkillLineAbilityMultiMap Data...
>> Loaded 9360 SkillLineAbility MultiMap Data in 142 ms
Loading SpellInfo custom attributes...
>> Loaded 96 spell custom attributes from DB in 86 ms
>> Loaded SpellInfo custom attributes in 529 ms
Loading SpellInfo diminishing infos...
>> Loaded SpellInfo diminishing infos in 59 ms
Loading SpellInfo immunity infos...
>> Loaded SpellInfo immunity infos in 49 ms
Loading PetFamilySpellsStore Data...
Loading Spell Totem models...
>> Loaded 200 spell totem model records in 94 ms
Loading GameObject models...
>> Loaded 8176 GameObject models in 155 ms
Loading Script Names...
>> Loaded 5954 ScriptNames in 11555 ms
Loading Instance Template...
>> Loaded 317 instance templates in 143 ms
Loading instances...
>> Loaded instances in 794 ms
Loading Localization strings...
>> Loaded 106648 creature locale strings in 2658 ms
>> Loaded 20376 gameobject_template_locale strings in 374 ms
>> Loaded 25125 Quest Template locale strings in 1869 ms
>> Loaded 227 Quest Offer Reward locale strings in 53 ms
>> Loaded 63 Quest Request Items locale strings in 43 ms
>> Loaded 20229 Quest Objectives locale strings in 290 ms
>> Loaded 1 PageText locale strings in 54 ms
>> Loaded 18 gossip_menu_option locale strings in 37 ms
>> Localization strings loaded in 5697 ms
Loading Account Roles and Permissions...
>> Loaded 697 permission definitions, 679 linked permissions and 4 default permissions in 185 ms
Loading Page Texts...
>> Loaded 2484 page texts in 114 ms
Loading Game Object Templates...
>> Loaded 47569 game object templates in 1157 ms
Loading Game Object template addons...
>> Loaded 44889 game object template addons in 190 ms
Loading Transport templates...
>> Loaded 69 transport templates in 69 ms
Loading Transport animations and rotations...
Loading Spell Rank Data...
>> Loaded 865 spell rank records in 12 ms
Loading Spell Required Data...
>> Loaded 21 spell required records in 50 ms
Loading Spell Group types...
>> Loaded 272 spell group definitions in 40 ms
Loading Spell Learn Skills...
>> Loaded 196 Spell Learn Skills from DBC in 145 ms
Loading SpellInfo SpellSpecific and AuraState...
>> Loaded SpellInfo SpellSpecific and AuraState in 47 ms
Loading Spell Learn Spells...
>> Loaded 56 spell learn spells, 875 found in Spell.dbc in 148 ms
Loading Spell Proc conditions and data...
>> Loaded 669 spell proc conditions and data in 45 ms
Generating spell proc data from SpellMap...
>> Generated spell proc data for 5135 spells in 30 ms
Loading Aggro Spells Definitions...
>> Loaded 20 SpellThreatEntries in 9 ms
Loading Spell Group Stack Rules...
>> Loaded 8 spell group stack rules in 39 ms
Loading NPC Texts...
>> Loaded 11372 npc texts in 111 ms
Loading Enchant Spells Proc datas...
>> Loaded 16 enchant proc data definitions in 9 ms
Loading Item Random Enchantments Table...
>> Loaded 34276 Item Enchantment definitions in 92 ms
Loading Disables
>> Loaded 5454 disables in 58 ms
Loading Items...
>> Loaded 104011 item templates in 2539 ms
Loading Item set names...
>> Loaded 625 item addon templates in 160 ms
>> Loaded 17 item script names in 1 ms
Loading Creature Model Based Info Data...
>> Loaded 65423 creature model based info in 449 ms
Loading Creature templates...
>> Loaded 110447 creature definitions in 5858 ms
Loading Creature template journals...
>> Loaded 45 creature template journal definitions in 70 ms
Loading Equipment templates...
>> Loaded 23784 equipment templates in 241 ms
Loading Creature template addons...
>> Loaded 24209 creature template addons in 188 ms
Loading Creature template scaling...
>> Loaded 26011 creature template scaling data in 91 ms
Loading Script Params...
>> Loaded 0 script param creature definitions. DB table `script_params` is empty.
Loading Reputation Reward Rates...
>> Loaded 14 reputation_reward_rate in 34 ms
Loading Creature Reputation OnKill Data...
>> Loaded 2054 creature award reputation definitions in 85 ms
Loading Reputation Spillover Data...
>> Loaded 28 reputation_spillover_template in 12 ms
Loading Points Of Interest Data...
>> Loaded 746 Points of Interest definitions in 93 ms
Loading Creature Base Stats...
>> Loaded 460 creature base stats in 85 ms
Loading Creature Data...
Could not load VMAP name:Transport: Howling Fjord Sister Mercy (Quest), id:594, x:31, y:39 (vmap rep.: x:31, y:39)
Could not load VMAP name:Transport: Howling Fjord Sister Mercy (Quest), id:594, x:32, y:39 (vmap rep.: x:32, y:39)
Could not load VMAP name:Transport: Howling Fjord Sister Mercy (Quest), id:594, x:31, y:38 (vmap rep.: x:31, y:38)
Could not load VMAP name:Transport: Howling Fjord Sister Mercy (Quest), id:594, x:32, y:38 (vmap rep.: x:32, y:38)
Could not load VMAP name:Transport: Orgrimmar to Thunder Bluff, id:647, x:32, y:32 (vmap rep.: x:32, y:32)
Could not load VMAP name:Transport: Orgrimmar to Thunder Bluff, id:647, x:31, y:32 (vmap rep.: x:31, y:32)

d:\trinitybuilder\source\spp-ashamanecore\src\common\collision\management\mmapmanager.cpp:199 in MMAP::MMapManager::loadMapImpl ASSERTION FAILED:
data
`

Updated:
worldserver.exe crash the same as jukatax said. Need help ASAP.
I really regret updating the repack. :-(    DEV PLEASE HELP....
If there is a way to reverse the update please help us.
Update: 
Just updated the RECPACK and yields the same result. PLEASE HELP.

**Comment by Gusthaddius** [comment]
Same Issue!

Tried Everything!

Reset database and nearly all options! Letting the Database to use the untest versions of uptades , but nothing works. 
![notworking](https://user-images.githubusercontent.com/35368364/47496422-06a48600-d857-11e8-95e2-f31861f932b2.png)
![notworking](https://user-images.githubusercontent.com/35368364/47496462-20de6400-d857-11e8-8714-fa716390dbe9.png)

**Comment by fly-man-** [comment]
Seems that the latest Vmaps and MMaps aren't included in the SPP. This might be the cause of this issue

Update: It's not the Vmaps / Mmaps as I have updated them and the error still persisted.

**Comment by wormogo** [comment]
Hi there! 

These are not connecting to Spp and came from ashamane. We can’t do anything with the issue until it is solved on ashamane.

**Comment by fly-man-** [comment]
@wormogo Then it might be best to make sure that the repository has a text that it's currently broken so people know what's going on.

A simple READTHIS file that explains the broken pieces might help a lot

**Comment by TheGiuxeppeh** [comment]
Fly-man is right. Approved.
