### ISSUE TITLE
Evade bug with normal mobs if hunter attack

### ISSUE THREAD

**Issue by istvandavid** [wormogo/Fixes_for_SPP_Project#95]
Mobs unatackable, if attack show evade text, and follow attacker. Bugs current only in hunter.

https://imgur.com/a/xAruY16

`Pet (GUID Full: 0x20000442400FF7000000000000000770 Type: Creature Entry: 16348 Low: 1904, entry 16348) has no pctFromOwnerArmor defined. Armor set to 1.`

https://pastebin.com/XTqkMMxP

**Comment by istvandavid** [comment]
New bug, paladin. https://imgur.com/a/GppTGqJ

https://pastebin.com/JLaGXwSn

**Comment by takasi689** [comment]
For hunter `Evade text` is showing because mob changes target from Pet~Player~Pet,since hunter has bug with his per working well.

**Comment by takasi689** [comment]
If you play with `Game Master` account you might get Evading texts too,because only player account can test game in best way. 😊
