### ISSUE TITLE
[Quest/Echo Isles] Proving Pit

### ISSUE THREAD

**Issue by TedfordKelly** [wormogo/Fixes_for_SPP_Project#99]
**Describe the bug**
The Captive Spitescale Scout doesn't leave the cage and is out of sight because of that. 

**Screenshots**
![screenshot 30](https://user-images.githubusercontent.com/45308918/49028784-7df56e80-f1a3-11e8-8229-240a973befcf.png)

**Comment by takasi689** [comment]
Abandon quest,take it again and leave door open you will be able to attack the target.
